version: '3.8'

services:
  app:
    build: .
    # image: ghcr.io/jaoafa/jaotanChatLogger3:latest
    volumes:
      - type: bind
        source: ./config/
        target: /app/config/
    init: true