# Node.js v14 と v16 でビルド・テストを実行する

name: Node CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14, 16]

    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v3

      - name: 🏗 Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: 📃 Check package.json definition
        id: package-json
        run: |
          # shellcheck disable=SC2086,SC2129
          compile=$(jq '.scripts | has("compile")' package.json)
          build=$(jq '.scripts | has("build")' package.json)
          generate=$(jq '.scripts | has("generate")' package.json)
          package=$(jq '.scripts | has("package")' package.json)
          lint=$(jq '.scripts | has("lint")' package.json)
          test=$(jq '.scripts | has("test")' package.json)

          echo "compile: $compile"
          echo "build: $build"
          echo "generate: $generate"
          echo "package: $package"
          echo "lint: $lint"
          echo "test: $test"

          # shellcheck disable=SC2086,SC2129
          echo "compile=$compile" >> $GITHUB_OUTPUT
          # shellcheck disable=SC2086,SC2129
          echo "build=$build" >> $GITHUB_OUTPUT
          # shellcheck disable=SC2086,SC2129
          echo "generate=$generate" >> $GITHUB_OUTPUT
          # shellcheck disable=SC2086,SC2129
          echo "package=$package" >> $GITHUB_OUTPUT
          # shellcheck disable=SC2086,SC2129
          echo "lint=$lint" >> $GITHUB_OUTPUT
          # shellcheck disable=SC2086,SC2129
          echo "test=$test" >> $GITHUB_OUTPUT

      - name: 🛠 Get yarn cache directory path
        id: yarn-cache-dir-path
        run: |
          # shellcheck disable=SC2086
          echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: 📦 Cache node_modules
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: 👨🏻‍💻 Install dependencies
        run: yarn

      - name: 👀 Run linter
        if: steps.package-json.outputs.lint == 'true'
        run: yarn lint

      - name: 🎁 Run package
        if: steps.package-json.outputs.package == 'true'
        run: yarn package

      - name: 🏃 Run compile
        if: steps.package-json.outputs.compile == 'true'
        run: yarn compile

      - name: 🏗️ Run build & generate (Nuxt.js)
        if: steps.package-json.outputs.build == 'true' && steps.package-json.outputs.generate == 'true'
        run: |
          yarn build
          yarn generate

      - name: 🧪 Run tests
        if: steps.package-json.outputs.test == 'true'
        run: yarn test

      - name: ☑️ Check Dependencies
        run: npx depcheck

      - name: Check exists dist directory
        id: check-dist
        run: |
          # shellcheck disable=SC2086
          echo "exists=$(test -d dist && echo true || echo false)" >> $GITHUB_OUTPUT

      - name: 📦 Upload artifact
        if: steps.check-dist.outputs.exists == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist